### ISSUE TITLE
Please fix SonyLIV , non DRM not downloading

### ISSUE THREAD

**Issue by shahidhasanzai** [denobisipsis/adownloader#178]
hello , please fix Sonyliv.com , non drm episodes also not downloading with indian vpn ,

https://www.sonyliv.com/shows/wagle-ki-duniya-1700000669/sweet-child-of-vandana-1000110241?watch=true

![image](https://user-images.githubusercontent.com/75906314/110193623-c6a63280-7e56-11eb-88a4-ded70f30d9da.png)

**Comment by shahidhasanzai** [comment]
pic is without vpn , with vpn also not downloading ,showing same 1 link found

**Comment by denobisipsis** [comment]
Fixed

**Comment by shahidhasanzai** [comment]
https://www.sonyliv.com/shows/wagle-ki-duniya-1700000669/srinivas-finds-an-old-letter-1000110174?watch=true

![image](https://user-images.githubusercontent.com/75906314/110206998-ee22ec80-7ea2-11eb-8bc9-ce97763159a0.png)


![Uploading image.png…]()

**Comment by shahidhasanzai** [comment]
Found...1 links 
Getting manifest m3u8...
Module m3 up to date

eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTUwMzQyNDQsImV4cCI6MTYxNjMzMDI0NCwiYXVkIjoiKi5zb255bGl2LmNvbSIsImlzcyI6IlNvbnlMSVYiLCJzdWIiOiJzb21lQHNldGluZGlhLmNvbSJ9.N6xuNmQzTXYLtfh19xW8Y0h4jfxHh2uX-9bi-b0rWTb41I0FfSERu5G5vkG8MpCzW-HHQfryeKmTScVHN-HwDFZUu6Yc1yuc_UkywLJwnuhknSBjba-xVCEQCKm5QoWebQZG73jJbO1iLjsvZfrgaQhvkR6mAOW_XohtHeI9Z_glsZx0pRV9oB0QvXnvuAOTYo5-JF2lfueBDGXa-F6gFhcuM4_CUQTGMNXmN9btVImN3xzLqJpspP2mI_lfc98C7voMOB36EClzVPhNFYc_J4r2KKjr56cI7ru7wj9FDjpzQTfDSScUTBjmYzURn1YCOCXMWaXbOXTcKv7r_tPUzj3V2pHc0exbWbUGFBQbv6YIdnZkPPapIkvOLpuku8up_L5ir-Ktlk0viFCsmzNO41s1MYCM76qbx-1V7lunyYzhRRGBVkujYapFxNWs7DvcXrKj_k4zty4t4zf4z313pGPalK1-P0VzHDjRZoyAoDVXhAlTZdZxd5FBVMGXK-Oi1KP-UMbNmmTiW9Mc006IvWhNDnyJuRiyb89vH-f1mB0KqS_2ahQ6-0UgFdQwOwASn3li2S49z9nK88F0YyNZdVLQ29kvPTSivJAPZ7kOYzx2efvvSG5FKJ-gw6OBNilF8RKMM-0T0UhRY3fQS2NaudaJ-QsTFe7ZGQZKJFx1908
1000110174
Found 1
Selected proxy from IN but unused cause you're there
You are in IN
Module nproxy up to date
Module brightcove up to date
Finished
Extract's error dll curl
Updating curl dll...
 good
Module redirector up to date
https://www.sonyliv.com/shows/wagle-ki-duniya-1700000669/srinivas-finds-an-old-letter-1000110174?watch=true
Searching streams...
Found...1 links 
Getting manifest m3u8...
Module m3 up to date

**Comment by shahidhasanzai** [comment]
Finished
Extract's error dll curl
Updating curl dll...
 good
Module redirector up to date
https://www.sonyliv.com/shows/wagle-ki-duniya-1700000669/sweet-child-of-vandana-1000110241?watch=true
Searching streams...
You're up to date
Actual minor version d11f621fb32b847f45a02a96cdc429a5
Checking minor...wait...
You have the latest major version v19
Checking latest...
Booting in 16 seconds
Running...
Ready...
 good
Thank you for contributing Shahidhasanzai1
Checking donation...
Donation...
Mux options false for internal use of ffmpeg. Dont change it if you dont know what are you doing
Structure...
	22-inichecks...set to Y
	15-getsubs...Y
	14-sout...#transcode{vcodec=mp4v,acodec=mpga,deinterlace,hq}:standard{access=file,mux=ts
	13-ydashwebm...false
	12-ydashmp4...false
	11-ychunk=...9000000
	10-muxoptions...false
	9-Audio output set to SAME
	8-Video output set to SAME
	7-Forcing proxy...N
	6-proxyuse...Use online proxies
	5-hdsparallel...set to 4
	4-hlsrelaunch...N
	3-m3delete...N
	2-m3parallel...set to 4
	1-fftemp not set
	0-Downloads folder set to C:\Adownloader\downloads
Options...
Adobe HDS funciona correctamente
AdobeHDS...
path...
SubtitleEdit...
modules...
rabcasm...
vlc...
ismdownloader...
ismdownloaderAVC1...
rtmpdump...
ffmpeg...
php...
SabreAMF...
external scripts...
curl...
7za...
aria2c...
curl...
Updated cacert.pem  Tue Jan 19 04:12:04 2021 GMT

Cacert...
Folders...
OK
Connection...
Inichecks...
Starting...
Adownloader Log...

**Comment by shahidhasanzai** [comment]
still not working with vpn ,non drm protect , after fix , give me new setup file of .exe

**Comment by denobisipsis** [comment]
Its the latest. Wait some days
